- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io"

- name: Update helm repo
  ansible.builtin.command: helm repo update

- name: Deploy latest version of Grafana chart inside monitoring namespace with values
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    chart_version: "{{ cilium_chart_version }}"
    kubeconfig: ./kubeconfig
    values:
      ipam:
        mode: kubernetes
